In [26]:
n = int(input())
k = 1
while k <= n*n:
    if k 
    print(k, end= "")
    print()
    k += 1


2
1
2
3
4


In [90]:
n = int(input())
for j in range(1,2):
    a = []
    for i in range(1,n*n+1):
        a.append(i)
    print(a)
count = 1
for h in a:
    count += 1
    if count <= 4:
        print(h)

4
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
1
2
3


In [68]:
R = int(input("Enter the number of rows:")) 
C = int(input("Enter the number of columns:")) 
  
# Initialize matrix 
matrix = [] 
print("Enter the entries rowwise:") 
  
# For user input 
for i in range(R):          # A for loop for row entries 
    a =[] 
    for j in range(C):      # A for loop for column entries 
         a.append(int(input())) 
    matrix.append(a) 
  
# For printing the matrix 
for i in range(R): 
    for j in range(C): 
        print(matrix[i][j], end = " ") 
    print() 

Enter the number of rows:2
Enter the number of columns:2
Enter the entries rowwise:
1
2
3
4
1 2 
3 4 


In [83]:
n = int(input())
R = n
C = n
matrix = []
for i in range(R):
    a = []
    for j in range(C):
        a.append(n)
    matrix.append(a)
for i in range(R): 
    for j in range(C): 
        print(matrix[i][j], end = " ") 
    print() 

4
4 4 4 4 
4 4 4 4 
4 4 4 4 
4 4 4 4 


In [130]:
n = int(input())
h = 0
if n %2 == 0:
    d = n//2
else:
    d = n//2+1
for r in range(0, n):
	s=''
	for c in range(1, n+1):
		if r<d:
			h = r*2
		elif r==d:
			h = d
		else:
			h = 1
		s+=str(h*n+c) + ' '
	print(s)

5
1 2 3 4 5 
11 12 13 14 15 
21 22 23 24 25 
16 17 18 19 20 
6 7 8 9 10 


In [103]:
n = int(input())
upper = int(n/2)+1
lower = n - upper
start_i_lower = 0

for i in range(0, upper):
    
    if i != 0:
        i = i + i
    start = n*i + 1
    end = start + n

    for j in range(start, end):
        print(j, end =" ")
    start_i_lower = i
    print()

start_i_lower -= 1

for i in range(0, lower):
    if(n%2 == 0):
        start_i_lower -= 1

    start = n*(start_i_lower-1) + 1
    end = start + n

    for j in range(1, n+1):
        print(j+n, end =" ")

print()

3
1 2 3 
7 8 9 
4 5 6 


In [114]:
import numpy as np
n = int(input())
a1 = np.arange(1, n*n+1)  
matrix = a1.reshape(n, n)
print(matrix)
for i in range(1,n+1):    
    for j in matrix:
        odd = []
        even = []
        if i % 2 == 0:
            even = even.append(j)
        else:
            odd = odd.append(j)
    print(odd,even)

4
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
None []
[] None
None []
[] None


In [135]:
import numpy as np 
def row_sum(arr) : 
    sum = 0
    for i in range(R) : 
        for j in range(C) :
            sum += arr[i][j] 
        print("Sum of",(i+1),"row:",sum) 
        sum = 0
        
def column_sum(arr) : 
    sum = 0    
    for i in range(C) : 
        for j in range(R) : 
            sum += arr[j][i] 
        print("Sum of",(i+1),"column:",sum) 
        sum = 0  

n = int(input())        
for i in range(1,n+1):
    str = input().split()
    R,C = int(str[0]),int(str[1])
    li = [[int(j) for j in input().split()] for i in range(n)]
    row_sum(li)
    column(li)
    print()

1
2 2
1 2


IndexError: list index out of range

In [147]:
import numpy as np 
  
def row_sum(arr) : 
    sum = 0
    for i in range(n) : 
        row = []
        for j in range(m) :
            sum += arr[i][j]
            row = row.append(sum)
        print('row',i,sum)
        sum = 0
    print(row)

def column_sum(arr) : 
    sum = 0    
    for i in range(m) : 
        col = []
        for j in range(n) : 
            sum += arr[j][i]
            col = col.append(sum)
        print('column',i,sum)
        sum = 0
    print(col)

n = int(input())


for i in range(1,n+1):
    str = input().split()
    n,m = int(str[0]),int(str[1])
    li = [[int(j) for j in input().split()] for i in range(n)]
    row_sum(li)
    print()
    column_sum(li)


1
2 2
1 2
3 4


AttributeError: 'NoneType' object has no attribute 'append'

In [142]:
print(row)

In [143]:
col