>>numerical python 
>>multidimensional array
--memory
--faster
--convenience
--functionality 

In [1]:
import numpy as np

In [2]:
a = [1,2,3]
b = np.array(a)
b

array([1, 2, 3])

In [3]:
a = [1,2,3]
b = np.array(a)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [6]:
a = [1,2,3,'a',4.5]
b = np.array(a,dtype=str)
b
#stores all elemnts of different type as string

array(['1', '2', '3', 'a', '4.5'], dtype='<U3')

In [7]:
a = [1,2,3,'a',4.5]
b = np.array(a*3,dtype=str)
print(b)

['1' '2' '3' 'a' '4.5' '1' '2' '3' 'a' '4.5' '1' '2' '3' 'a' '4.5']


In [8]:
b = np.ones(3,dtype=int)
b

array([1, 1, 1])

In [14]:
b = np.zeros(3,dtype=int)
b

array([0, 0, 0])

In [11]:
b = np.ones((2,3),dtype=int)
b
#matrix

array([[1, 1, 1],
       [1, 1, 1]])

In [18]:
b = np.full(3,5)
#fill array with 3 5's
a = np.full((3,3),5)
print(b)
print(a)

[5 5 5]
[[5 5 5]
 [5 5 5]
 [5 5 5]]
